### ISSUE TITLE
ERROR: [reposync] failed to fetch file x86_64-repodata

### ISSUE THREAD

**Issue by AngryPhantom** [DBLouis/void-linux-liquorix#1]
Hello!

Trying to add your repository as written in the Readme:

```
Add the following line in your XBPS configuration (e.g. /etc/xbps.d/10-liquorix.conf).
repository=https://dblouis.github.io/void-linux-liquorix/<arch>
```

Changed `<arch>` to `x86_64` and see this error after syncing with `xbps-install -Su`:

```
[*] Updating repository `https://dblouis.github.io/void-linux-liquorix/x86_64/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://dblouis.github.io/void-linux-liquorix/x86_64/x86_64-repodata': Not Found
```

What am I doing wrong?

Thank you.

**Comment by DBLouis** [comment]
"arch" in this case is the CPU architecture name (zen, skylake...), not the instructions set. Only zen or generic are available here. Please choose generic unless you have a zen CPU like me.

**Comment by AngryPhantom** [comment]
@DBLouis Oh, I'm sorry, I didn't get it at first. No problem. Closing :)

**Comment by AngryPhantom** [comment]
One last question: is your email contact@...xyz still valid? I've sent you a letter in order to not to spam here. Thanks.
